name: Build-Test-Unit
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Repo chekout
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm i
    - name: Run unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo "mr.d.dimitrov"
